{
  "formatVersion": "1.1",
  "component": {
    "group": "io.specmatic",
    "module": "specmatic-kafka",
    "version": "0.25.0-TRIAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-kafka-0.25.0-TRIAL.jar",
          "url": "specmatic-kafka-0.25.0-TRIAL.jar",
          "size": 696413,
          "sha512": "ac2e002b0ad66724648ff50543332c046a5113452540f12500c442d46b0b1c99e439557b8bee42549c952013635924d32fcc38e03725cfb0534048e3163609d7",
          "sha256": "a0d1b97f922f5d0cd8119dedce282d3cfcb9267b83b5bc66a88924fadc6891f5",
          "sha1": "6a57114843c534d5d0aea8043ffa01c3beb044a6",
          "md5": "3dbd76b86c2c35bd19522eb2a5fb1681"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.kafka",
          "module": "kafka_2.13",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.6.0"
          }
        },
        {
          "group": "org.apache.curator",
          "module": "curator-framework",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "org.apache.curator",
          "module": "curator-test",
          "version": {
            "requires": "5.5.0"
          }
        },
        {
          "group": "com.asyncapi",
          "module": "asyncapi-core",
          "version": {
            "requires": "1.0.0-RC2"
          },
          "excludes": [
            {
              "group": "com.fasterxml.jackson.core",
              "module": "jackson-databind"
            },
            {
              "group": "com.fasterxml.jackson.module",
              "module": "jackson-module-kotlin"
            },
            {
              "group": "com.fasterxml.jackson.dataformat",
              "module": "jackson-dataformat-yaml"
            }
          ]
        },
        {
          "group": "info.picocli",
          "module": "picocli",
          "version": {
            "requires": "4.7.6"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-nop",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "io.specmatic",
          "module": "specmatic-core",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-netty",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-core",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-server-content-negotiation",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-jackson",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-jvm",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.16.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.0"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.24.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.9.3"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.6.0"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-reporting",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.fusesource.jansi",
          "module": "jansi",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20231013"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        }
      ],
      "files": [
        {
          "name": "specmatic-kafka-0.25.0-TRIAL.jar",
          "url": "specmatic-kafka-0.25.0-TRIAL.jar",
          "size": 696413,
          "sha512": "ac2e002b0ad66724648ff50543332c046a5113452540f12500c442d46b0b1c99e439557b8bee42549c952013635924d32fcc38e03725cfb0534048e3163609d7",
          "sha256": "a0d1b97f922f5d0cd8119dedce282d3cfcb9267b83b5bc66a88924fadc6891f5",
          "sha1": "6a57114843c534d5d0aea8043ffa01c3beb044a6",
          "md5": "3dbd76b86c2c35bd19522eb2a5fb1681"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
